config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'
  root 'static_pages#about'
  get 'bio', to: 'static_pages#bio'
  get 'tattoo', to: 'static_pages#tattoo'
  get 'art', to: 'static_pages#art'
  get 'photography', to: 'static_pages#photography'
  get 'appointments', to: 'static_pages#appointments'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController

  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def bio
  end

  def tattoo
  end

  def art
  end

  def photography
  end

  def appointments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home_page/index.html.erb
<div class="hero">
  <br />
  <div class="text-center">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <h1>BRIAN HENRY</h1>
    <h4>BLACKSAGE TATTOO</h4>
    <br />
    </div>
   </div>
</div>

<br />
<br />
  <div class="row feature text-center">
    <div class="col-12 col-sm">
     <%= image_tag '2.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm">
      <%= image_tag '1.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm">
      <%= image_tag '3.jpg', class: 'img-fluid' %>
  </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Pompiere|Yantramanav" rel="stylesheet">
    <title>Bhens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
      <%= link_to 'HOME', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'BIO', bio_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
       <%= link_to 'TATTOO', tattoo_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'ART', art_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'PHOTOGRAPHY', photography_path, class: 'nav-link' %>
      </li>
  </div>
   <li class="navbar-nav mr-auto mt-2 mt-md-0">
      <%= link_to 'APPOINTMENTS', appointments_path, class: 'nav-link' %>
      </li>
  </nav>

   <%= yield %>
  </div>
  <div id="footer">
      <div class="container">
        <b>TO BOOK AN APPOINTMENT</b>
        <br />
        <%= link_to 'CONTACT ME' %>
      </li>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/appointments.html.erb
<div class="staticbg">

<!-- www.123formbuilder.com script begins here -->
<script type="text/javascript" defer src="//www.123formbuilder.com/embed/3796332.js" data-role="form" data-default-width="650px"></script>
<!-- www.123formbuilder.com script ends here -->

</div>

app/views/static_pages/art.html.erb
<div class="staticbg">
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>
THERES GONNA BE SOME ART N SHIT HERE TOO MF
</h1>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

</div>

app/views/static_pages/bio.html.erb
<div class="staticbg">
  <div class="bio">
<h1>
<br />
<br />
<br />
<br />
<br />
I'm Brian Henry. AKA BHens.
<br />
I tattoo
<br />
I art
<br />
I photograph
<br />
<br />
<br />
<br />
<br />
<br />
<br />
</h1>
</div>
</div>

app/views/static_pages/photography.html.erb
<div class="staticbg">
<br />

<div class="booyah-box col-10 offset-1">
  <br />
  <br />
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'Pslide1.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'Pslide2.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'Pslide3.jpg', class: 'd-block img-fluid' %>
    </div>    
    <div class="carousel-item">
      <%= image_tag 'Pslide4.jpg', class: 'd-block img-fluid' %>
    </div>   
     <div class="carousel-item">
      <%= image_tag 'Pslide5.jpg', class: 'd-block img-fluid' %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br />
<br />
</div>

app/views/static_pages/tattoo.html.erb
<div class="staticbg">
<br />

<div class="booyah-box col-10 offset-1">
  <br />
  <br />
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
    </div>    
    <div class="carousel-item">
      <%= image_tag 'slider4.jpg', class: 'd-block img-fluid' %>
    </div>   
     <div class="carousel-item">
      <%= image_tag 'slider5.jpg', class: 'd-block img-fluid' %>
    </div>    
    <div class="carousel-item">
      <%= image_tag 'slider6.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider7.jpg', class: 'd-block img-fluid' %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br />
<br />
</div>